---
title: "R Notebook"
output: html_notebook
---
```{r include=FALSE}
library(tidyverse)
library(dplyr)

source("metrics.r")
source("common.r")
source("experiment_data.r")

## Loading in the data
exp_name <- "slots_exp_final1"

data_exps <- loadSlotsExperimentData(exp_name)

data_all <- data_exps
```


These are some other plots

```{r}

title <- function(mechanism_name, proj_pref_type) {
    pretty_mechanism_name = mechanism_name_map[[mechanism_name]]
    pretty_proj_pref_type = paste("(", proj_pref_type, ")", sep = "")
    paste(pretty_mechanism_name, pretty_proj_pref_type, sep = " - ")
}

```


# RUNTIMES
```{r}
for (ppt in levels(data_all$proj_pref_type)){
    for (mech in levels(data_all$mechanism)) {
        
        data_filtered <- data_all %>% filter(mechanism == mech & proj_pref_type == ppt)
        
        pretty_title = title(mech, ppt)
        
        plot <- ggplot(data_filtered, aes(x = num_slots, y = duration_ms / 1000, group = num_slots)) +
                    geom_boxplot() +
                    # geom_jitter(position=position_jitter(0.2)) +
                    facet_grid(num_students ~ project_pressure) +
                    ylim(0, 90) + 
                    labs(
                        title = title(mech, ppt),
                        y = "Duration (sec)",
                        x = "# slots (per project topic)"
                    )
        
        print(plot)
        
        path = paste("plots", "slots_exp", "runtimes", ppt, sep = "/")
        filename <- paste(path, paste("runtimes_", pretty_title, ".png", sep = ""), sep ="/")
        # ggsave(filename,
        #        device = "png", width = 120, height = 120, units = "mm", pointsize = 100
        # )
    }
}
```

# QUALITY (AUPCR)
```{r}
for (ppt in levels(data_all$proj_pref_type)){
    for (mech in levels(data_all$mechanism)) {
        
        pretty_title = title(mech, ppt)
        
        data_filtered <- data_all %>%
            filter(trial == 0 & mechanism == mech & proj_pref_type == ppt) %>%
            mutate(
                aupcr = map2(num_projects, profile_all, calc_aupcr) %>% unlist
            )
        
        
        plot <- ggplot(data_filtered, aes(x = num_slots, y = aupcr, group = num_slots)) +
                    geom_boxplot() +
                    # geom_jitter(position=position_jitter(0.2)) +
                    facet_grid(num_students ~ project_pressure) +
                    ylim(0.5, 1) +
                    labs(
                        title = title(mech, ppt),
                        y = "AUPCR",
                        x = "# slots (per project topic)"
                    )
        
        print(plot)
        
        path = paste("plots", "slots_exp", "aupcr", ppt, sep = "/")
        filename <- paste(path, paste("aupcr_", pretty_title, ".png", sep = ""), sep ="/")
        ggsave(filename,
               device = "png", width = 120, height = 120, units = "mm", pointsize = 100
        )
    }
}

```

```{r}
for (ppt in levels(data_all$proj_pref_type)){
    for (mech in levels(data_all$mechanism)) {
        
        pretty_title = title(mech, ppt)
        
        data_filtered <- data_all %>%
            filter(trial == 0 & mechanism == mech & proj_pref_type == ppt) %>%
            mutate(
                "henk" = map2(1, profile_all, calc_aupcr),
                "aupcr" = map2(num_projects, profile_all, calc_aupcr),
                "piet" = 1
            )
        
        
        plot <- ggplot(data_filtered, aes(x = num_slots, y = aupcr, group = num_slots)) +
                    geom_boxplot() +
                    # geom_jitter(position=position_jitter(0.2)) +
                    facet_grid(num_students ~ project_pressure) +
                    ylim(0.5, 1) +
                    labs(
                        title = title(mech, ppt),
                        y = "AUPCR",
                        x = "# slots (per project topic)"
                    )
        
        print(plot)
        
        # path = paste("plots", "slots_exp", "aupcr", ppt, sep = "/")
        # filename <- paste(path, paste("aupcr_", pretty_title, ".png", sep = ""), sep ="/")
        # ggsave(filename,
        #        device = "png", width = 120, height = 120, units = "mm", pointsize = 100
        # )
    }
}
```


# WORST RANK PLOTS
```{r}
# WORST RANK
for (ppt in levels(data_all$proj_pref_type)){
    for (mech in levels(data_all$mechanism)) {
        
        pretty_title = title(mech, ppt)
        
        data_filtered <- data_all %>%
            filter(trial == 0 & mechanism == mech & proj_pref_type == ppt) %>%
            mutate(
                worst_rank = map(profile_all, worst_obtained_rank) %>% unlist
            )
        
        # y-limit must be shared over all plots within group???
        
        plot <- ggplot(data_filtered, aes(x = num_slots, y = worst_rank, group = num_slots)) +
                    geom_boxplot() +
                    # geom_jitter(position=position_jitter(0.2)) +
                    facet_grid(num_students ~ project_pressure) +
                    # ylim(0.5, 1) + 
                    labs(
                        title = title(mech, ppt),
                        y = "Worst rank",
                        x = "# slots (per project topic)"
                    )
        
        print(plot)
        
        path = paste("plots", "slots_exp", "worst_rank", ppt, sep = "/")
        filename <- paste(path, paste("worst_", pretty_title, ".png", sep = ""), sep ="/")
        # ggsave(filename,
        #        device = "png", width = 120, height = 120, units = "mm", pointsize = 100
        # )
    }
}
```

# AVG RANK
```{r}
for (ppt in levels(data_all$proj_pref_type)){
    for (mech in levels(data_all$mechanism)) {
        
        pretty_title = title(mech, ppt)
        
        data_filtered <- data_all %>%
            filter(trial == 0 & mechanism == mech & proj_pref_type == ppt) %>%
            mutate(
                avg_rank = map(profile_all, avg_rank) %>% unlist
            )
        
        # y-limit must be shared over all plots within group???
        
        plot <- ggplot(data_filtered, aes(x = num_slots, y = avg_rank, group = num_slots)) +
                    geom_boxplot() +
                    # geom_jitter(position=position_jitter(0.2)) +
                    facet_grid(num_students ~ project_pressure) +
                    # ylim(0.5, 1) + 
                    labs(
                        title = title(mech, ppt),
                        y = "AVG rank",
                        x = "# slots (per project topic)"
                    )
        
        print(plot)
        
        path = paste("plots", "slots_exp", "worst_rank", ppt, sep = "/")
        filename <- paste(path, paste("worst_", pretty_title, ".png", sep = ""), sep ="/")
        # ggsave(filename,
        #        device = "png", width = 120, height = 120, units = "mm", pointsize = 100
        # )
    }
}
```

# AVG RANK (WEIGHTED)
```{r}
for (ppt in levels(data_all$proj_pref_type)){
    for (mech in levels(data_all$mechanism)) {
        
        pretty_title = title(mech, ppt)
        
        data_filtered <- data_all %>%
            filter(trial == 0 & mechanism == mech & proj_pref_type == ppt) %>%
            mutate(
                avg_rank_w = map(profile_all, avg_weighted_rank) %>% unlist
            )
        
        # y-limit must be shared over all plots within group???
        
        plot <- ggplot(data_filtered, aes(x = num_slots, y = avg_rank_w, group = num_slots)) +
                    geom_boxplot() +
                    # geom_jitter(position=position_jitter(0.2)) +
                    facet_grid(num_students ~ project_pressure) +
                    # ylim(0, 2000) + 
                    labs(
                        title = title(mech, ppt),
                        y = "AVG rank",
                        x = "# slots (per project topic)"
                    )
        
        print(plot)
        
        path = paste("plots", "slots_exp", "worst_rank", ppt, sep = "/")
        filename <- paste(path, paste("worst_", pretty_title, ".png", sep = ""), sep ="/")
        # ggsave(filename,
        #        device = "png", width = 120, height = 120, units = "mm", pointsize = 100
        # )
    }
}
```


# JUST RANKS (WEIGHTED)
```{r}
for (ppt in levels(data_all$proj_pref_type)) {
    for (mech in levels(data_all$mechanism)) {
        
        
        pretty_title = title(mech, ppt)
        
        
        data_filtered <- data_all %>%
            filter(trial == 0 & mechanism == mech & proj_pref_type == ppt)
        
        
        # for (slots in levels(data_filtered$num_slots)) {
        #     for (students in levels(data_filtered$num_students)) {
        #         for (ppres in levels(data_filtered))
        #     }
        # }
        
        zzz <- data_filtered %>%
            mutate(rank = map(profile_all, rank_profile))
        xxx <- zzz %>% unchop(rank)
        
        # y-limit must be shared over all plots within group???
        
        plot <- ggplot(xxx, aes(x = num_slots, y = rank, group = num_slots)) +
                    geom_violin() +
                    # geom_jitter(position=position_jitter(0.2)) +
                    facet_grid(num_students ~ project_pressure) +
                    ylim(0, 20) + 
                    labs(
                        title = title(mech, ppt),
                        y = "AVG rank",
                        x = "# slots (per project topic)"
                    )
        
        print(plot)
        
        path = paste("plots", "slots_exp", "worst_rank", ppt, sep = "/")
        filename <- paste(path, paste("worst_", pretty_title, ".png", sep = ""), sep ="/")
        # ggsave(filename,
        #        device = "png", width = 120, height = 120, units = "mm", pointsize = 100
        # )
    }
}

# num_slots
# num_students
# project_pressure
```

```{R}

rank_profile("124|73|3")

```