---
title: "R Notebook"
output: html_notebook
---
```{r include=FALSE}
library(tidyverse)
library(dplyr)
library(ggh4x)
# library(ggridges)

source("metrics.r")
source("common.r")
source("experiment_data.r")

## Loading in the data
exp_name = "grouping_soft_att2_eps"

data_pregroup_soft <- loadGroupingSoftExperimentData(exp_name)

title <- function(mechanism_name, proj_pref_type) {
    pretty_mechanism_name = mechanism_name_map[[mechanism_name]]
    pretty_proj_pref_type = paste("(", proj_pref_type, ")", sep = "")
    paste(pretty_mechanism_name, pretty_proj_pref_type, sep = " - ")
}

```

This file includes visualizations of the synthetic instances with pregrouping.

# Thesis: runtimes
```{r, fig.height=4, fig.width=11, warning=FALSE}
data_pregroup_soft_f <- data_pregroup_soft %>%
    filter(trial == 0) |>
    mutate(
        mechanism_short = map(mechanism, ~ mechanism_name_map_short[[levels(mechanism)[.]]]) %>% unlist,
        proj_pref_type = factor(proj_pref_type, ordered = T,
                            levels = c("linear_perturbed_4", "realistic", "random"),
                            labels = c("m unan", "3-peaked", "rnd")
        )
    ) |>
    filter(mechanism_short != 'BEPSys') |>

plot <- ggplot(data_pregroup_soft_f,
               aes(x = interaction(proj_pref_type, mechanism_short),
                   y = duration_ms / 1000,
                   fill = mechanism_short
               )
       ) +
   
     geom_boxplot(outlier.shape = NA) +
        scale_color_discrete() +
    
     geom_point(aes(shape = project_pressure, color = project_pressure), alpha = 0.9, size = 1, position = position_dodge(width = 0.5)) +
        scale_color_discrete(name = "project pressure", type = c("#E69F00", "#0072B2", "#D55E00")) +
    
#    "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00"

    # facet_grid(num_students ~ project_pressure) +
    facet_wrap(vars(num_students)) + 
    
    # ylim(0, 90) + 
    # scale_y_log10() +
    
    scale_y_continuous(
        trans='log10',
        oob = scales::oob_squish_infinite,
        breaks = scales::trans_breaks('log10', function(x) 10^x),
        labels = scales::trans_format('log10', scales::math_format(10^.x))
    ) +
    
    guides(x = guide_axis_nested(angle = 0)) + 
    
    labs(
        y = "Duration (sec, log10)",
        x = "Mechanism x Project pref. distribution combination",
        fill = "mechanism",
        shape = "project pressure"
    ) +
    
    theme(legend.position = "bottom")


print(plot)

path = paste("plots", "thesis", sep = "/")
filename <- paste(path, paste0("synth_group_maxsoft_runtimes_chia_fair", ".png"), sep ="/")
ggsave(filename,
       device = "png", width = 260, height = 90, units = "mm", dpi = 300, pointsize = 12
)

# ggplot(data_all, aes(x = mechanism, y = duration_ms / 1000, group = mechanism)) +
#     geom_boxplot() 
#     ylim(0, 100)
```


# Thesis:  Quality 
Histogram like mirrored plot. Only Chia vs Fair, no 100% pregrouping case

```{r, fig.height = 10}
thesis_quality <- function(studs, ppt, pressure) {
    pretty_title = paste0("students: ", studs,
                          ", project pref dist: ", ppt,
                          ", project pressure: ", switch(pressure, "TIGHT" = "tight (1.0)", "MID" = "mid (1.5)"))
    
    data_filtered <- loadGroupingSoftExperimentData(exp_name) %>%
        filter(
            trial == 0 &
            gd == "MAX_ONLY" & # Only the MAX-SIZE pregroupings
            project_pressure == pressure &
                proj_pref_type == ppt &
                num_students == studs &
                mechanism != 'BepSys (reworked) - Borda' &
                pregroup_type != '100 %'
            ) %>%
        mutate(
                mechanism_short = map(mechanism, ~ mechanism_name_map_short[[levels(mechanism)[.]]]) %>% unlist
            )
    
    zzz <- data_filtered %>%
        mutate(
            profile_solo = map(profile_singles, rank_profile),
            profile_singles = NULL,
            profile_preg = map(profile_pregrouped, rank_profile),
            profile_pregrouped = NULL,
            profile_unsat = map(profile_unsatpregroup, rank_profile),
            profile_unsatpregroup = NULL,
            profile_all = map(profile_all, rank_profile)
        ) %>%
        pivot_longer(
            cols = starts_with("profile"),
            names_to = "student_type",
            names_prefix = "profile_",
            values_to = "rank"
        ) %>%
        filter(
            student_type != 'all'
        )

    xxx <- zzz %>% unchop(rank)
    xxx$student_type <- factor(xxx$student_type, levels = c( "solo", "preg", "unsat")) #"all",
    
    fair_subset <- xxx |> filter(mechanism_short == 'Fair')
    chia_subset <- xxx |> filter(mechanism_short == 'Chia')
    
    # print(fair_subset)
    # print(chia_subset)
    
    # Make the numbers proportional, so that we can see per facet, per mechanism, per rank the proportion of students
    proportions <- function (data) {
        data |>
            group_by(pregroup_type, pregroup_proj_pref_type, student_type, rank) |>
            summarize(n_type = n()) |> ungroup() |>
            add_count(pregroup_type, pregroup_proj_pref_type, wt = n_type) |>
            ## calculate correct proportion for each facet
            mutate(prop = n_type / n)
    }
    
    plot <- ggplot() + 
        # geom_density(
        #     outline.type = "both", bw = 0.5,
        #     data = fair_subset,
        #     position = 'stack',
        #     aes(x = rank, y = after_stat(density),
        #         fill = student_type)
        #     ) +
        
        # Fair mechanism: above the 0
        geom_col(
            data = fair_subset |> proportions(),
            aes(x = rank, y = prop, fill = student_type)
        ) +
        
        # geom_density(
        #     outline.type = "both", bw = 0.5,
        #     data = chia_subset,
        #     position = 'stack',
        #     aes(x = rank, y = -after_stat(density),
        #         fill = student_type)
        #     ) +
        
        # Chia mechanism: below the 0
        geom_col(
            data = chia_subset |> proportions(),
            aes(x = rank, y = -prop, fill = student_type)
        ) +
        
        geom_hline(yintercept = 0, linewidth = 0.1, alpha = 0.4) +
        
        facet_grid(pregroup_type ~ pregroup_proj_pref_type, shrink = T) +
        
        labs(
            subtitle = pretty_title,
            y = "students (percent)",
            x = "rank",
            fill = "student type"
        ) +
        
        # scale_x_continuous(trans = "log2", limits = c(1, max(xxx$rank))) +
        # scale_y_continuous(trans = "log") +
        
        scale_x_continuous(breaks = \(...) {
            # ensure the x-axis starts at 1, not 0 as no such rank exists
            # hacky: wrap the break_extended and fix it's output
            res <- scales::breaks_extended(n = 10, Q = c(1, 5))(...)
            res[1] <- 1
            res
        }) +
        
        scale_y_continuous(breaks = scales::breaks_extended(n = 7, Q = c(0.05, 0.1)),
                           minor_breaks = scales::breaks_width(0.1),
                           labels = scales::label_percent()
        ) +
        
        scale_fill_manual(drop = FALSE, values = c("#0fb783", "#FBAE04", "#AE04FB") ) +
        
        theme(
            legend.position = "bottom"
            # legend.key.size = unit(5, "mm")
        )
            
}

# for (pressure in levels(data_pregroup_soft$project_pressure)) {
for (pressure in c("TIGHT", "MID")) {
    
    print(thesis_quality(200, 'realistic', pressure))
    path = paste("plots", "thesis", sep = "/")
    filename <- paste(path, paste0("synth_group_maxsoft_quality_200_", pressure, ".png"), sep ="/")
    ggsave(filename,
           device = "png", width = 230, height = 200, units = "mm", dpi = 300, pointsize = 12
    )
}

```

# VIOLIN PLOT - Quality comparison between types (Only Chia vs Fair, no 100%)
```{r, fig.height = 15}
# unique(data_all$mechanism)
for (studs in levels(ordered(unique(data_pregroup_soft$num_students)))) {
    for (ppt in levels(data_pregroup_soft$proj_pref_type)) {
        for (pressure in levels(data_pregroup_soft$project_pressure)) {
            
            pretty_title = paste(paste(studs, "@", spe=""), ppt, pressure, sep = " - ")
            
            data_filtered <- data_pregroup_soft %>%
                filter(
                    trial == 0 &
                    project_pressure == pressure &
                        proj_pref_type == ppt &
                        num_students == studs &
                        mechanism != 'BepSys (reworked) - Borda' &
                        pregroup_type != '100 %'
                    ) %>% #& pregroup_proj_pref_type == preg_pref_type)
                mutate(
                        mechanism_short = map(mechanism, ~ mechanism_name_map_short[[levels(mechanism)[.]]]) %>% unlist
                    )
            
            map(data_filtered$profile_unsatpregroup, rank_profile)
            
            zzz <- data_filtered %>%
                mutate(
                    profile_solo = map(profile_singles, rank_profile),
                    profile_singles = NULL,
                    profile_preg = map(profile_pregrouped, rank_profile),
                    profile_pregrouped = NULL,
                    
                    profile_unsat = map(profile_unsatpregroup, rank_profile),
                    profile_unsatpregroup = NULL,
                    profile_all = map(profile_all, rank_profile)
                ) %>%
                pivot_longer(
                    cols = starts_with("profile"),
                    names_to = "student_type",
                    names_prefix = "profile_",
                    values_to = "rank"
                )
            
            xxx <- zzz %>% unchop(rank)
            xxx$student_type <- factor(xxx$student_type, levels = c("all", "solo", "preg", "unsat"))
            
            # y-limit must be shared over all plots within group???
            
            plot <- ggplot(xxx, aes(x = student_type, y = rank, group = student_type)) +
                        geom_violin(scale = "count") +
                        # geom_jitter(position=position_jitter(0.2)) +
                        facet_grid(pregroup_type + mechanism_short ~ pregroup_proj_pref_type, scales = "free_x") +
                        # ylim(0, 20) + 
                        labs(
                            title = pretty_title,
                            y = "rank",
                            x = "student grouping type"
                        )
            
            print(plot)
            
            # path = paste("plots", "slots_exp", "worst_rank", ppt, sep = "/")
            # filename <- paste(path, paste("worst_", pretty_title, ".png", sep = ""), sep ="/")
            # # ggsave(filename,
            # #        device = "png", width = 120, height = 120, units = "mm", pointsize = 100
            # # )
        }
    }
}

```

# Old attempts at quality visualization

```{r, fig.height = 15}
# unique(data_all$mechanism)
for (studs in levels(ordered(unique(data_pregroup_soft$num_students)))) {
    ppt <- "realistic"
    # for (ppt in levels(data_all$proj_pref_type)) {
        for (pressure in levels(data_pregroup_soft$project_pressure)) {
        # for (b in seq(0.5, 1, by = 0.1)) {
     
            pretty_title = paste(paste(studs, "@", spe=""), ppt, pressure, sep = " - ")
            
            data_filtered <- data_pregroup_soft %>%
                filter(
                    trial == 0 &
                    project_pressure == pressure &
                        proj_pref_type == ppt &
                        num_students == studs &
                        mechanism != 'BepSys (reworked) - Borda' &
                        pregroup_type != '100 %'
                    ) %>% #& pregroup_proj_pref_type == preg_pref_type)
                mutate(
                        mechanism_short = map(mechanism, ~ mechanism_name_map_short[[levels(mechanism)[.]]]) %>% unlist
                    )
            
            map(data_filtered$profile_unsatpregroup, rank_profile)
            
            zzz <- data_filtered %>%
                mutate(
                    profile_solo = map(profile_singles, rank_profile),
                    profile_singles = NULL,
                    profile_preg = map(profile_pregrouped, rank_profile),
                    profile_pregrouped = NULL,
                    profile_unsat = map(profile_unsatpregroup, rank_profile),
                    profile_unsatpregroup = NULL,
                    profile_all = map(profile_all, rank_profile)
                ) %>%
                pivot_longer(
                    cols = starts_with("profile"),
                    names_to = "student_type",
                    names_prefix = "profile_",
                    values_to = "rank"
                ) %>%
                filter(
                    student_type != 'all'
                )

            xxx <- zzz %>% unchop(rank)
            xxx$student_type <- factor(xxx$student_type, levels = c( "solo", "preg", "unsat")) #"all",
            
            # y-limit must be shared over all plots within group???
            
            fair_subset <- subset(xxx, mechanism_short == 'Fair')
            chia_subset <- subset(xxx, mechanism_short == 'Chiarandini')
            
            br <- seq(0, max(xxx$rank), by = 5)
            br[1] = 1
            
            br <- unique(xxx$rank);
            br <- pretty(xxx$rank);
            
            trans_log1p_fix <- scales::trans_new(
                name = "log1p_fix",
                transform = function (x) {
                    sign(x) * log(1 + abs(x), 10) 
                },
                inverse = function (x) {
                    sign(x) * (10 ^ abs(x) - 1)
            })
            
            trans_sqrt_fix <- scales::trans_new(
                name = "sqrt_fix",
                transform = function(x) {
                    # base::print("call to transform")
                    # base::print(x)
                    r <- sign(x) * scales::sqrt_trans()$transform(abs(x))
                    # base::print("result of transform")
                    # base::print(r)
                    return(r)
                },
                inverse = function(x) {
                    # base::print("call to inverse")
                    # base::print(x)
                    r <- sign(x) * scales::sqrt_trans()$inverse(abs(x))
                    # base::print("result of inverse")
                    # base::print(r)
                    return(r)
                },
                domain = c(-1, 1)
            )
            
            percent_abs <- function(x, ...) {
                scales::percent(abs(x), ...)
            }
            
            log2(1 + 0.2)
            exp(1 + log2(0.2))
            
            #xxx, aes(x = rank, y = after_stat(count), group = student_type) #, color = student_type)) +
            plot <- ggplot() +
                
                geom_histogram(
                    data = fair_subset,
                    # boundary = -0.5,
                    binwidth = 1,
                        ## there are 12 cells (facets), we want y to be the proportion/percent
                        aes(x = rank, y = after_stat(count / sum(count) / 12 * 100), fill = student_type)
                    ) +
                
                geom_histogram(
                    data = chia_subset,
                    # boundary = -0.5,
                    binwidth = 1,
                        aes(x = rank, y = -after_stat(count / sum(count) / 12 * 100), fill = student_type)
                    ) +
                
                facet_grid(pregroup_type ~ pregroup_proj_pref_type) +
                labs(
                    title = pretty_title,
                    y = "students (proportional)",
                    x = "rank"
                ) +
                
                scale_x_continuous(breaks = br) +
                
                coord_trans(y = trans_sqrt_fix) +
                scale_y_continuous(labels = percent_abs) +
                # "solo", "preg", "unsat"
                # "#F8766D" "#00BA38" "#619CFF"
                # "#0bd000", "#619CFF", "#ffea19"
                scale_fill_manual(drop = FALSE, values = c("#0fb783", "#FBAE04", "#AE04FB") ) +
                theme(legend.key.size = unit(5, "mm"), legend.position = "bottom")
                    
                        
            
            print(plot)
        
            path = paste("plots", exp_name, "quality", sep = "/")
            filename <- paste(path, paste("histo_", paste(studs, ppt, pressure, sep = "_"), ".png", sep = ""), sep ="/")
            # ggsave(filename,
            #        device = "png", width = 400, height = 250, units = "mm", pointsize = 100
            # )
        }
    
}
```

```{r fig.width=15, fig.height=8}
data_pregroup_soft <- loadGroupingSoftExperimentData("grouping_soft_att2_eps") |>
    augment_with_short_mechanism_name()


trans_log1p_fix <- scales::trans_new(
    name = "log1p_fix",
    transform = function (x) {
        sign(x) * log(1 + abs(x), 10) 
    },
    inverse = function (x) {
        sign(x) * (10 ^ abs(x) - 1)
})

trans_sqrt_fix <- scales::trans_new(
    name = "sqrt_fix",
    transform = function(x) {
        r <- sign(x) * scales::sqrt_trans()$transform(abs(x))
        return(r)
    },
    inverse = function(x) {
        # base::print("call to inverse")
        r <- sign(x) * scales::sqrt_trans()$inverse(abs(x))
        return(r)
    },
    domain = c(-1, 1)
)

percent_abs <- function(x, ...) {
    scales::percent(abs(x), ...)
}

# unique(data_all$mechanism)
for (studs in levels(ordered(unique(data_pregroup_soft$num_students)))) {
    # ppt <- "realistic"
    for (ppt in levels(data_pregroup_soft$proj_pref_type)) {
        for (pressure in levels(data_pregroup_soft$project_pressure)) {
            for (preg_dist in levels(data_pregroup_soft$gd)) {
     
                pretty_title = paste(paste(studs, "@", spe=""), ppt, pressure, preg_dist, sep = " - ")
                
                data_filtered <- data_pregroup_soft |>
                    filter(
                        trial == 0 &
                        project_pressure == pressure &
                        proj_pref_type == ppt &
                        num_students == studs &
                        mechanism_short != "BEPSys" &
                        pregroup_type != '100 %' &
                        gd == preg_dist
                    )
                
                # map(data_filtered$profile_unsatpregroup, rank_profile)
                
                xxx <- data_filtered |>
                    mutate(
                        profile_solo = map(profile_singles, rank_profile),
                        profile_singles = NULL,
                        profile_preg = map(profile_pregrouped, rank_profile),
                        profile_pregrouped = NULL,
                        profile_unsat = map(profile_unsatpregroup, rank_profile),
                        profile_unsatpregroup = NULL,
                        profile_all = NULL
                    ) |>
                    pivot_longer(
                        cols = starts_with("profile"),
                        names_to = "student_type",
                        names_prefix = "profile_",
                        values_to = "rank"
                    ) |>
                    unchop(rank)
                
                xxx$student_type <- factor(xxx$student_type, levels = c( "solo", "preg", "unsat")) #"all",
                
                # y-limit must be shared over all plots within group???
                
                fair_subset <- subset(xxx, mechanism_short == 'Fair')
                chia_subset <- subset(xxx, mechanism_short == 'Chiarandini')
                
                if (nrow(xxx) == 0)
                    next
                
                br <- seq(0, max(xxx$rank), by = 5)
                br[1] = 1
                
                br <- unique(xxx$rank);
                br <- pretty(xxx$rank);
                
                log2(1 + 0.2)
                exp(1 + log2(0.2))
                
                if (br[1] > 1)
                    br <- prepend(br, 1)
                else
                    br[1] <- 1
                
                #xxx, aes(x = rank, y = after_stat(count), group = student_type) #, color = student_type)) +
                plot <- ggplot() +
                    
                    geom_histogram(
                        data = fair_subset,
                        # boundary = -0.5,
                        binwidth = 1,
                        ## there are 12 cells (facets), we want y to be the proportion/percent
                        aes(x = rank, y = after_stat(count / sum(count) / 12 * 100), fill = student_type, group = student_type)
                    ) +
                    
                    geom_histogram(
                        data = chia_subset,
                        # boundary = -0.5,
                        binwidth = 1,
                        aes(x = rank, y = -after_stat(count / sum(count) / 12 * 100), fill = student_type)
                    ) +
                    
                    facet_grid(pregroup_type ~ pregroup_proj_pref_type) +
                    labs(
                        title = pretty_title,
                        y = "students (proportional)",
                        x = "rank"
                    ) +
                    
                    scale_x_continuous(breaks = br) +
                    
                    coord_trans(y = trans_sqrt_fix) +
                    scale_y_continuous(labels = percent_abs) +
                    # "solo", "preg", "unsat"
                    # "#F8766D" "#00BA38" "#619CFF"
                    # "#0bd000", "#619CFF", "#ffea19"
                    scale_fill_manual(drop = FALSE, values = c("#0fb783", "#FBAE04", "#AE04FB") ) +
                    theme(legend.key.size = unit(5, "mm"), legend.position = "bottom")
                        
                            
                
                print(plot)
                
                filename <- paste("plots/thesis/", paste(paste("grouped-soft_", studs, ppt, pressure, preg_dist, sep = "_"), ".png", sep = ""), sep = "")
                # ggsave(filename,
                #        device = "png", width = 300, height = 160, units = "mm", pointsize = 100
                # )
            }
        }
    }
}
```
