---
title: "Thesis plots - synthetic experiments"
output: html_notebook
---

```{r}
library(tidyverse)
library(dplyr)
library(ggh4x)
library(patchwork)

source("metrics.r")
source("common.r")
source("experiment_data.r")
```

## Synthetic - size/slots - runtimes
```{r, fig.height = 10}

plot_size_runtimes <- function() {
    data_slots <- loadSlotsExperimentData("slots_exp_final1") |>
            filter(num_students > 50 & trial == 1) |> #project_pressure == "LOOSE" &  & num_slots == 1
            filter((num_students == 200 & project_pressure == "LOOSE") | num_students == 600) |>
            augment_with_short_mechanism_name() |>
            augment_with_nice_projectpref_name()

    plot <- ggplot(data_slots, aes(x = mechanism_short, y = duration_ms / 1000, group = interaction(mechanism_short, num_slots), color = num_slots)) +
            geom_boxplot() +

            facet_grid(num_students + project_pressure ~ projectpref_short, labeller = partial(label_value, multi_line = FALSE)) +
        
            scale_y_continuous(trans = "log2", oob = scales::oob_squish_any,
                               labels = \(z) scales::label_math(expr = 2^.x)(log2(z))
            ) +

            scale_x_discrete(guide = guide_axis(angle = 30)) +
            labs(
                title = NULL,
                y = "Duration (sec)",
                x = "Mechanism",
                color = "# slots"
            )
}

print(plot_size_runtimes())

ggsave(plot = plot_size_runtimes(),
       filename = paste("plots", "thesis", "size_slots_runtimes.png", sep = "/"),
       device = "png", width = 300, height = 150, units = "mm", dpi = 300, pointsize = 12
)

```

## Synthetic - size/slots - quality
```{r, fig.width=13}
plot_slots_quality_withslots <- function () {
    data_slots <- loadSlotsExperimentData("slots_exp_final1") |>
        augment_with_nice_projectpref_name() |>
        filter(trial == 0 & projectpref_short != "unanimous" & num_students == 200) |>
        augment_with_short_mechanism_name() |>
        filter(mechanism_short != "Fair")
    
    worst <- max(data_slots$worst_rank)
    data_slots_aug <- data_slots |> mutate(worst_rank_scaled = worst_rank / worst)
    
    plot <- ggplot(data_slots_aug, 
                   aes(x = interaction(num_slots, mechanism_short),
                       y = aupcr,
                       group = interaction(num_slots, mechanism_short),
                   )
            ) +
        
                geom_boxplot(aes(color = num_slots)) +
        
                geom_point(
                    aes(y = worst_rank_scaled),
                    shape = 8, size = 2, stroke = 0.2,
                    position = position_dodge(width = 0.7), 
                    color = "black"
                ) +
        
                scale_y_continuous(sec.axis = sec_axis(name = "Worst rank", ~ . * worst)) +
        
                scale_shape_identity() + 
        
                facet_grid(project_pressure ~ projectpref_short, shrink = FALSE) +
        
                guides(x = "axis_nested") +
        
                labs(
                    title = NULL,
                    y = "AUPCR",
                    x = expression('Mechanism' %*% ' pressure (slots)'),
                    color = "", fill = ""
                ) + 
                theme(legend.position = "none", legend.direction = "horizontal", legend.key.size = unit(5, "mm"))
}

print(plot_slots_quality_withslots())

ggsave(plot = plot_slots_quality_withslots(),
       filename = paste("plots", "thesis", "size_slots_quality.png", sep = "/"),
       device = "png", width = 330, height = 206, units = "mm", dpi = "print"
)
```

# Group size bounds - runtimes
```{r fig.height=10}

plot_gsb_runtime <- function (param_num_studs) {
    data_groupsizb <- loadGroupSizeBoundsExperimentData("gsc_exp_final1") |>
            filter(num_students == param_num_studs) |>
            augment_with_short_mechanism_name() |>
            augment_with_nice_projectpref_name()
    
    filtered_data <- data_groupsizb
    
    plot <- ggplot(filtered_data,
                   aes(x = mechanism_short,
                       y = ceiling(duration_ms / 1000),
                       group = mechanism_short,
                       color = mechanism_short
                   )
            ) +
        
            geom_boxplot() +
    
            facet_grid(gsc_max ~ gsc_min,
                       labeller = labeller(gsc_max = ~ paste("u:", .),
                                           gsc_min = ~ paste("l:", .))
            ) +
            
            scale_y_continuous(trans = "log2", oob = scales::oob_squish_any,
                               labels = \(z) scales::label_math(expr = 2^.x)(log2(z))
            ) + 
        
                scale_x_discrete(guide = guide_axis(angle = 30)) +
        
                labs(
                    title = paste(param_num_studs, "students"),
                    y = "Duration (sec)",
                    x = expression('Mechanism'),
                    color = "Mechanism"
                ) +
                theme(legend.position = "none", legend.direction = "horizontal")
}

print(plot_gsb_runtime(200) + plot_gsb_runtime(600))

ggsave(plot = plot_gsb_runtime(200) + plot_gsb_runtime(600) + plot_layout(axis_titles = "collect"),
       filename = "plots/thesis/synth_gsb_runtimes_200600.png",
       device = png, width = 330, height = 200, units = "mm", dpi = "print", pointsize = 12
)

```

# GSB - quality (worst_rank+aupcr)
```{r fig.height=8}


plot_gsb_q <- function(num_studs, metric) {
    metric_pretty <- new.env()
    metric_pretty[['aupcr']] = 'AUPCR'
    metric_pretty[['worst_rank']] = 'Worst Rank'
    
    data_gsb_q <- loadGroupSizeBoundsExperimentData("gsc_exp_final1") |>
        augment_with_short_mechanism_name() |>
        augment_with_nice_projectpref_name()

    filtered_data <- data_gsb_q |>
        filter(trial == 1 & mechanism_short == "Chia") |>
        filter(num_students == num_studs) |>
        filter(proj_pref_type == "realistic" & project_pressure == 'TIGHT')
    
    # scale worst rank to the main y-axis, which is AUPCR that goes from 0 to 1
    # worst <- max(filtered_data$worst_rank)
    # data_aug <- filtered_data |> mutate(worst_rank = worst_rank / worst)
    
    data_aug <- filtered_data |>
            pivot_longer(aupcr | worst_rank, names_to = "metric_name", values_to = "metric_value") |>
            filter(metric_name == metric)
    
    # print(data_aug)
    
    plot <- ggplot(data_aug,
                   aes(x = projectpref_short,
                       group = projectpref_short,
                   )
            ) +
        
            geom_boxplot(aes(y = metric_value)) +
                   
            # geom_boxplot(aes(y = aupcr, color = mechanism_short)) +
            # 
            # geom_boxplot(aes(y = worst_rank_scaled),
            #              stroke = 0.2,
            #              color = "black",
            #              shape = 8, size = 0.2, position = position_dodge(width = 0.7)
            # ) +
        
            # scale_y_continuous(sec.axis = sec_axis(name = "Worst rank", ~ . * worst)) +
    
            facet_grid(gsc_max ~ gsc_min,
                       labeller = labeller(gsc_max = ~ paste("u:", .),
                                           gsc_min = ~ paste("l:", .))
            ) +
        
            # guides(x = guide_axis_nested(angle = 90)) + 
            # scale_x_discrete(guide = guide_axis(angle = 30)) +
                
            labs(
                title = NULL, #paste("Group size bounds scaling -", num_studs, "students"),
                y = metric_pretty[[metric]],
                x = "",
                # color = "Mechanism: "
            ) +
        
            theme(legend.position = "none", legend.direction = "horizontal")
}

print(plot_gsb_q(200, 'aupcr') + plot_gsb_q(200, 'worst_rank'))

ggsave(plot = plot_gsb_q(200, 'aupcr') + plot_gsb_q(200, 'worst_rank'),
       filename = paste0("plots/thesis/synth_gsb_qual_focused", 200, ".png"),
       device = "png", width = 330, height = 206, units = "mm", dpi = "print")
       
# ggsave(plot = plot_gsb_q(600),
#        filename = paste0("plots/thesis/synth_gsb_qual_", 600, ".png"),
#        device = "png", width = 330, height = 206, units = "mm", dpi = "print")
```

## Alternative approach, plot both aupcr and worst rank as boxplots in the same plot.
An older attempt. I have done something similar now for the thesis plot, see above.
```{r fig.height=8}
## new idea: more granular, plot both aupcr and worst rank as boxplots
plot_gsb_q <- function(num_studs) {
    filtered_data <- loadGroupSizeBoundsExperimentData("gsc_exp_final1") |>
        augment_with_short_mechanism_name() |>
        augment_with_nice_projectpref_name() |>
        filter(num_students == num_studs)
    
    # scale worst rank to the main y-axis, which is AUPCR that goes from 0 to 1
    worst <- max(filtered_data$worst_rank)
    data_aug <- filtered_data |> mutate(worst_rank_scaled = worst_rank / worst) |>
        pivot_longer(
            cols = c("aupcr", "worst_rank_scaled"),
            names_to = "metric_name",
            values_to = "metric_value"
        )
    
    plot <- ggplot(data_aug,
               aes(x = interaction(projectpref_short, mechanism_short, metric_name),
                   group = interaction(projectpref_short, mechanism_short, metric_name),
                   )
            ) +
        
            geom_boxplot(aes(y = metric_value, color = mechanism_short), stroke = 0.2) +
        
    
            facet_grid(gsc_max ~ gsc_min,
                       labeller = labeller(gsc_max = ~ paste("u:", .),
                                           gsc_min = ~ paste("l:", .))
            ) +
        
            guides(x = guide_axis_nested(angle = 90)) + 

            scale_y_continuous(sec.axis = sec_axis(name = "Worst rank", ~ . * worst)) +
                
            labs(
                title = paste("Group size bounds scaling -", num_studs, "students"),
                y = "AUPCR",
                x = "",
                color = "Mechanism: "
            ) +
            theme(legend.position = "none", legend.direction = "horizontal")
}

print(plot_gsb_q(200))

```
